# -*- mode: ruby -*-
# vi: set ft=ruby :

# Copyright (c) 2015 Intracom S.A. Telecom Solutions. All rights reserved.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License v1.0 which accompanies this distribution,
# and is available at http://www.eclipse.org/legal/epl-v10.html


# ------------------------------------------------------------------------------
# VM configuration.
# ------------------------------------------------------------------------------
odlp2_vm_basebox = 'nstat_vm_base'
user = ENV['USER']
odlp2_vm_private_network_ip_host = '192.168.63.1'

# ------------------------------------------------------------------------------
odlp2_vm_ram_vm_01 = '4096'
odlp2_vm_cpus_vm_01 = '2'
odlp2_vm_private_network_ip_vm_01 = '<IP_address>'
odlp2_vm_hostname_vm_01 = 'vm01'
uid_01 = ENV.has_key?('VM_UID') ? '_' + ENV['VM_UID'].split('-')[0] : '_' + odlp2_vm_private_network_ip_vm_01
odlp2_vm_name_vm_01 = 'odlp2_ubuntu_box_'  + user + uid_01 + '_vm01'


odlp2_vm_ram_vm_02 = '4096'
odlp2_vm_cpus_vm_02 = '2'
odlp2_vm_private_network_ip_vm_02 = '<IP_address>'
odlp2_vm_hostname_vm_02 = 'vm02'
uid_02 = ENV.has_key?('VM_UID') ? '_' + ENV['VM_UID'].split('-')[0] : '_' + odlp2_vm_private_network_ip_vm_02
odlp2_vm_name_vm_02 = 'odlp2_ubuntu_box_'  + user + uid_02 + '_vm02'
# ------------------------------------------------------------------------------
# RUNNING_ENV options: 'with-proxy', 'no-proxy'
# ------------------------------------------------------------------------------
RUNNING_ENV = 'with-proxy'

# configure proxy settings
# ------------------------------------------------------------------------------
if RUNNING_ENV == 'with-proxy'
    http_proxy = 'http:/<IP_address>:<port_number>'
    puts '--------------------------------------------------------'
    puts 'running: with-proxy RUNNING_ENV'
     if !Vagrant.has_plugin?('vagrant-proxyconf')
         abort("                -vagrant-proxyconf plugin missing.
                -install it manually by typing:
--------------------------------------------------------
                vagrant plugin install vagrant-proxyconf
--------------------------------------------------------")
     end
elsif RUNNING_ENV == 'no-proxy'
    puts '--------------------------------------------------------'
    puts 'running: no-proxy RUNNING_ENV'
else
    puts 'RUNNING_ENV not set'
end


Vagrant.configure(2) do |config|

  config.ssh.username = 'vagrant'
  config.ssh.password = 'vagrant'

    if RUNNING_ENV == 'with-proxy'
        config.proxy.http = http_proxy
        config.proxy.https = http_proxy
        config.proxy.no_proxy = 'localhost,127.0.0.1,'+odlp2_vm_private_network_ip_vm_01+','+odlp2_vm_private_network_ip_vm_02+','+odlp2_vm_private_network_ip_host
    end

    #TODO: change rsync to nfs
    config.vm.synced_folder '.', '/vagrant', type: 'rsync'

    #If tty is not available
    config.ssh.shell = 'bash -c "BASH_ENV=/etc/profile exec bash"'

# ------------------------------------------------------------------------------
# ------------------------------------------------------------------------------
# ------------------------------------------------------------------------------
# ------------------------------------------------------------------------------

    config.vm.define odlp2_vm_name_vm_01 do |machine|
        machine.vm.box = odlp2_vm_basebox
        machine.vm.host_name = odlp2_vm_hostname_vm_01 + '.' + odlp2_vm_hostname_vm_01
        machine.vm.network :private_network, ip: odlp2_vm_private_network_ip_vm_01

        machine.vm.provider :virtualbox do |vb|
            # Display the VirtualBox GUI when booting the machine
            # vb.gui = true

            # Customize the amount of memory on the VM:
            vb.memory = odlp2_vm_ram_vm_01
            vb.cpus = odlp2_vm_cpus_vm_01
        end

        machine.vm.provider :libvirt do |libvirt|
            libvirt.memory = odlp2_vm_ram_vm_01
            libvirt.cpus = odlp2_vm_cpus_vm_01
            libvirt.management_network_name = 'vagrant-libvirt-new'
            libvirt.management_network_address = '192.168.124.0/24'
        end

    end
# ------------------------------------------------------------------------------
# ------------------------------------------------------------------------------
# ------------------------------------------------------------------------------
# ------------------------------------------------------------------------------
# ------------------------------------------------------------------------------
    config.vm.define odlp2_vm_name_vm_02 do |machine|
        machine.vm.box = odlp2_vm_basebox
        machine.vm.host_name = odlp2_vm_hostname_vm_02 + '.' + odlp2_vm_hostname_vm_02
        machine.vm.network :private_network, ip: odlp2_vm_private_network_ip_vm_02

        machine.vm.provider :virtualbox do |vb|
            # Display the VirtualBox GUI when booting the machine
            # vb.gui = true
            # Customize the amount of memory on the VM:
            vb.memory = odlp2_vm_ram_vm_02
            vb.cpus = odlp2_vm_cpus_vm_02
        end

        machine.vm.provider :libvirt do |libvirt|
            libvirt.memory = odlp2_vm_ram_vm_02
            libvirt.cpus = odlp2_vm_cpus_vm_02
            libvirt.management_network_name = 'vagrant-libvirt-new'
            libvirt.management_network_address = '192.168.124.0/24'
        end

    end

end
