# -*- mode: ruby -*-
# vi: set ft=ruby :

# Copyright (c) 2015 Intracom S.A. Telecom Solutions. All rights reserved.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License v1.0 which accompanies this distribution,
# and is available at http://www.eclipse.org/legal/epl-v10.html


# ------------------------------------------------------------------------------
# VM configuration.
# ------------------------------------------------------------------------------
nstat_vm_basebox = 'nstat_vm_base'
nstat_nodes_number = 4
nstat_node_names = ['nodecontroller', 'nodemininet', 'nodenstat', 'nodecbench']

nstat_node_vm_ram = '2048'
nstat_node_vm_cpus = '1'

nstat_nodes_private_network_ip = '192.168.10.20' # the first IP address in the NSTAT VMs IP Address range

# ------------------------------------------------------------------------------
# RUNNING_ENV options: 'with-proxy', 'no-proxy'
# ------------------------------------------------------------------------------
RUNNING_ENV = 'no-proxy'

# configure proxy settings
# ------------------------------------------------------------------------------
if RUNNING_ENV == 'with-proxy'
    http_proxy = 'http:/<IP_address>:<port_number>'
    puts '--------------------------------------------------------'
    puts 'running: with-proxy RUNNING_ENV'
     if !Vagrant.has_plugin?('vagrant-proxyconf')
         abort("                -vagrant-proxyconf plugin missing.
                -install it manually by typing:
--------------------------------------------------------
                vagrant plugin install vagrant-proxyconf
--------------------------------------------------------
                re-run: vagrant up")
     end
elsif RUNNING_ENV == 'no-proxy'
    puts '--------------------------------------------------------'
    puts 'running: no-proxy RUNNING_ENV'
else
    puts 'RUNNING_ENV not set'
end
     kostas = ['1', '2']
     no_proxy_nstat_nodes = Array.new
    (1..nstat_nodes_number).each do |nstat_vm|
        last_two_ip_digits = nstat_nodes_private_network_ip[-2..-1].to_i
        new_last_two_ip_digits = last_two_ip_digits + (nstat_vm - 1)
        base_ip = nstat_nodes_private_network_ip[0..-3]
        nstat_nodes_private_network_ip_inst = base_ip + new_last_two_ip_digits.to_s

        no_proxy_nstat_nodes[nstat_vm] = nstat_nodes_private_network_ip_inst.to_s
        #puts no_proxy_nstat_nodes[nstat_vm]

    end
    final_string = no_proxy_nstat_nodes.join(",")
    puts final_string
exit
Vagrant.configure(2) do |config|

    config.ssh.username = 'vagrant'
    config.ssh.password = 'vagrant'

    if RUNNING_ENV == 'with-proxy'
        config.proxy.http = http_proxy
        config.proxy.https = http_proxy
        config.proxy.no_proxy = 'localhost,127.0.0.1,192.168.10.15,192.168.10.16,192.168.10.17,192.168.10.18,192.168.10.19,192.168.10.20,192.168.10.21,192.168.10.30,192.168.10.31,192.168.10.31'
    end

    #If tty is not available
    config.ssh.shell = 'bash -c "BASH_ENV=/etc/profile exec bash"'

# ------------------------------------------------------------------------------
# Provision NSTAT nodes
# ------------------------------------------------------------------------------
    nstat_vm_hostname = 'NSTATnode'
    (1..nstat_nodes_number).each do |nstat_vm|
        temp_name = nstat_node_names[nstat_vm]
        puts temp_name
    end
end
