# -*- mode: ruby -*-
# vi: set ft=ruby :

# Copyright (c) 2015 Intracom S.A. Telecom Solutions. All rights reserved.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License v1.0 which accompanies this distribution,
# and is available at http://www.eclipse.org/legal/epl-v10.html


# ------------------------------------------------------------------------------
# VM configuration.
# ------------------------------------------------------------------------------

# make a new nstat_vm_basebox based on 'ubuntu/trusty64'
# https://atlas.hashicorp.com/ubuntu (latest version)
# vagrant box update (for updating to the latest official box)
# ------------------------------------------------------------------------------
nstat_vm_basebox = 'ubuntu/trusty64'
nstat_vm_ram = 1024
nstat_vm_cpus = 1

Vagrant.configure(2) do |config|

    config.ssh.username = 'vagrant'
    config.ssh.password = 'vagrant'

    config.ssh.shell = 'bash -c "BASH_ENV=/etc/profile exec bash"'

    config.vm.define 'nstat_vm_base' do |nstat_machine|
#        nstat_machine.vm.network :private_network, ip: "192.168.160.50",
#            :libvirt__network_name => 'nstat'

      nstat_machine.vm.box = nstat_vm_basebox
        nstat_machine.vm.provider :libvirt do |libvirt|
            libvirt.memory = nstat_vm_ram
            libvirt.cpus = nstat_vm_cpus
        end

    end

# ------------------------------------------------------------------------------
# Provisioning actions
# ------------------------------------------------------------------------------
    p = File.expand_path(__FILE__)
    print p
    exit
    #config.vm.provision :shell, privileged: true, :path => 'provision.sh'
    #config.vm.provision :shell, privileged: true, inline: 'apt-get clean'

end
